AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp-rake.rb"
